name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main] # main 브랜치에 푸시될 때 실행
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm" # yarn 사용시 'yarn'으로 변경

      - name: Install dependencies
        run: npm ci # yarn 사용시 'yarn install --frozen-lockfile'

      - name: Build
        run: npm run build # yarn 사용시 'yarn build'
        # env:
        # Vite 환경변수들 (필요시 추가)
        # VITE_API_URL: ${{ secrets.VITE_API_URL }}

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: route-optimzer # Cloudflare Pages 프로젝트 이름
          directory: dist # Vite는 dist 폴더에 빌드 결과물 생성
          # gitHubToken: ${{ secrets.GITHUB_TOKEN }}
